version: '3'
services:
  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri
    ports:
      - "32400:32400"
    volumes:
      - /mnt/docker/plex/database:/config
      - /mnt/media:/media
    environment:
      - PLEX_CLAIM=claim-LTwAjK-jcMp8UYUkHe8z
        #      - dev/shm:/transcode
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri
    ports:
      - "8096:8096"
    volumes:
      - /mnt/docker/jellyfin/config:/config
      - /mnt/docker/jellyfin/cache:/cache
      - /mnt/media:/media
