version: "3"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    restart: unless-stopped
    network_mode: host
    devices:
      - /dev/dri:/dev/dri
    ports:
      - "32400:32400"
    volumes:
      - /mnt/docker/plex/:/config
      - /mnt/media/music:/media/music
      - /mnt/media/pics:/media/pics
      - /mnt/media/movies-and-tv:/media/movies-tv
    environment:
      - PUID=998
      - PGID=1002
      - TZ=America/Chicago
      - VERSION=docker
      - PLEX_CLAIM=claim-uBLpUwuhpGTVoWSBSWid
        #      - dev/shm:/transcode
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri
    ports:
      - "8096:8096"
    volumes:
      - /mnt/docker/jellyfin/config:/config
      - /mnt/docker/jellyfin/cache:/cache
      - /mnt/media:/media
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_SCHEDULE: "0 0 4 * * *"
      TZ: America/Chicago

  stirling-pdf:
    image: frooodle/s-pdf:latest
    #ports:
    # - '8080:8080'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pdf.rule=Host(`pdf.drum-mirfak.ts.net`)"
      - "traefik.http.routers.pdf.entrypoints=websecure"
      - "traefik.http.routers.pdf.tls=true"
      - "traefik.http.routers.pdf.tls.certresolver=myresolver"
      - "traefik.http.services.pdf.loadbalancer.server.port=8080"
    volumes:
      - /mnt/docker/pdf/trainingData:/usr/share/testdata #Required for extra OCR languages
      - /mntdocker/pdf/extraConfigs:/configs
      - /mnt/docker/pdf/customFiles:/customFiles/
      - /mnt/docker/pdf/logs:/logs/
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false
      - LANGS=en_US
    networks:
      - traefik
networks:
  traefik:
    external: true
